name: SonarCloud Scan

on:
  push:
    branches:
      - main  # Modifier selon votre branche par défaut
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Scan before AFL
        run: |
         ls
        
      - name: Build with AFL
        run: |
          # Télécharger AFL
          wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
          tar -xzf afl-latest.tgz
          cd afl-2.52b
          sudo make install

      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v2
        with:
          organization: matt-vaude # Remplacez par votre organisation SonarCloud
          token: ${{ secrets.SONAR_TOKEN }} # Utilisez votre jeton SonarCloud

      - name: Scan folder
        run: | 
          cd build_wrapper_output_directory
          ls

      - name: Run build-wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make
          

      - name: SonarCloud Scan
        run: sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=matt-vaude -Dsonar.projectKey=fuzzanalyse -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
