name: SonarCloud Scan

on:
  push:
    branches:
      - main  # Modifier selon votre branche par défaut
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with AFL
        run: |
          # Télécharger AFL
          wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
          tar -xzf afl-latest.tgz
          cd afl-2.52b
          make && sudo make install

      - name: Build 
        run: |
          make

      - name: Run AFL
        run: |
          afl-fuzz -i in -o out ./fuzzgoat @@

      - name: SonarCloud Scan
        run: sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=matt-vaude -Dsonar.projectKey=fuzz -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=build

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
