name: SonarCloud Scan

on:
  push:
    branches:
      - main  # Modifier selon votre branche par défaut
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with AFL
        run: |
          # Télécharger AFL
          wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
          tar -xzf afl-latest.tgz
          cd afl-2.52b
          make && sudo make install

      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: matt-vaude # Remplacez par votre organisation SonarCloud
          token: ${{ secrets.SONAR_TOKEN }} # Utilisez votre jeton SonarCloud


      - name: SonarCloud Scan
        run: sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=matt-vaude -Dsonar.projectKey=fuzz -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=make

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
